package enums;

public enum ConfigType {
	DATA_DIR, APPS_DIR, DRIVERS_DIR, PAGEDEF_DIR, SUITE_DIR, SCREENSHOTS_DIR, PLATFORM, PLATFORM_VER, DEVICE_NAME, BROWSER, APP_URL, APP_FILE_NAME, APP_PACKAGE, ACTIVITY_MAIN, UDID, APPIUM_URL, XCODE_CONF, IOS_AUTOMATION_NAME, ANDROID_AUTOMATION_NAME, ALERT_BEHAVIOR, IMPLICIT_WAIT, EXPLICIT_WAIT, SWIPE_TOP_FRACTION, SWIPE_DOWN_FRACTION, SWIPE_WAIT, SCROLL_PIXEL_COUNT, SCRREENSHOT_TSTAMP, SCREENSHOTS_ON, SCREENSHOT_ONLY_ON_ERROR, NO_RESET, DATASHEET
}
